# Generated by Django 2.2.5 on 2020-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('dateReleased', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mainGenre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreID', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistID', models.IntegerField(primary_key=True, serialize=False)),
                ('playlistName', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('genreID', models.IntegerField()),
                ('artist', models.CharField(max_length=50)),
                ('albumID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='pass', max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('dateJoined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('songID', models.IntegerField()),
            ],
            options={
                'unique_together': {('username', 'songID')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('username', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songID', models.IntegerField()),
                ('playlistID', models.IntegerField()),
            ],
            options={
                'unique_together': {('songID', 'playlistID')},
            },
        ),
    ]
