# Generated by Django 3.0.5 on 2020-04-11 22:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='spotifyuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(db_column='artist', on_delete=django.db.models.deletion.CASCADE, to='spotify.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='mainGenre',
            field=models.ForeignKey(db_column='mainGenre', on_delete=django.db.models.deletion.PROTECT, to='spotify.Genre'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='createdBy',
            field=models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='playlistID',
            field=models.ForeignKey(db_column='playlistID', on_delete=django.db.models.deletion.CASCADE, to='spotify.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlistsongs',
            name='songID',
            field=models.ForeignKey(db_column='songID', on_delete=django.db.models.deletion.CASCADE, to='spotify.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='albumID',
            field=models.ForeignKey(db_column='albumID', on_delete=django.db.models.deletion.CASCADE, to='spotify.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(db_column='artist', on_delete=django.db.models.deletion.CASCADE, to='spotify.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genreID',
            field=models.ForeignKey(db_column='genreID', on_delete=django.db.models.deletion.PROTECT, to='spotify.Genre'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='artist',
            field=models.ForeignKey(db_column='artist', on_delete=django.db.models.deletion.CASCADE, to='spotify.Artist'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='songID',
            field=models.ForeignKey(db_column='songID', on_delete=django.db.models.deletion.CASCADE, to='spotify.Song'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
